### PR TITLE
Change JavaPlugin to Plugin

### PR DESCRIPTION
**Pull request by failutee**
Please, I'm begging you 😭

### CODE REVIEW

**Comment by TechnicallyCoded** [comment]
Please explain your reasoning

**Comment by failutee** [comment]
> Please explain your reasoning


There is no major reason, simply compatibility with other projects, everyone uses the Plugin interface and today, when I wanted to use your lib, I was surprised when I had to make a slight change and change Plugin to JavaPlugin

**Comment by TechnicallyCoded** [comment]
> @failutee Would you mind to update this PR to make two constructors? For Plugin and JavaPlugin to maintain compatibility. If not, I'll make a separate PR with those changes

Unless someone is using reflection to instantiate FoliaLib, Plugin being a supertype of JavaPlugin should allow it to just work with no modifications to constructors. Did I miss something?

**Comment by TechnicallyCoded** [comment]
You would be recompiling with the library attached. There is not case in which you compiled the plugin with folialib of a different version. The relocations that are required avoid this exact issue. Any dev that relocates the lib will not be interacting with anyone else's loaded classes.

**Comment by TechnicallyCoded** [comment]
It's not a plugin nor an API, and has no intention of being so, such behavior will not be supported.

**Review by TechnicallyCoded — APPROVED** [review]

**Pull request merged**
