### PR TITLE
Add support for task consumers

### PR DESCRIPTION
**Pull request by NahuLD**
This PR seeks to add support for consumed wrapped tasks that would be compatible with both Folia and Bukkit.
Feel free to request any changes if you think appropriate.

Thanks for the wrapper!

### CODE REVIEW

**Comment by TechnicallyCoded** [comment]
I love the idea and the PR is clean but there are a few issues:
- You aren't making changes to the dev branch. The dev branch is completely restructured and a simple merge won't resolve this.. I would love to see your changes in the dev branch soon ;)
- This lib needs to work on old versions of java as its goal is making full cross-compatiblity with new and old servers/plugin easy. Therefore, please don't use records. Trust me, I would love it if we didn't have to support old versions too... 🤷 
- (Minor: Make sure to document the API usability of consumers in the BukkitScheduler, it didn't exist in 1.13.1 but does since 1.13.2)
- (Minor: Also, avoid updating dependencies in a PR unless that's the goal of the PR. But that by itself doesn't matter enough to reject a PR =P)

The feature you are suggesting is really good, I would have merged it had the top 2 issues not been present.

**Comment by NahuLD** [comment]
Hello, thanks for the review and sorry for not responding earlier (I was out for a break). 
I will solve these issues today and push the changes!

**Comment by NahuLD** [comment]
I have resorted to a hacky workaround to make it work with legacy versions, I will need to test it before asking for a review!

**Comment by NahuLD** [comment]
Sorry for taking this long to get back to this. Everything seems to be working as intended, feel free to give it a whirl!

**Pull request closed without merging**
